### ISSUE TITLE
对于各个型号的雷达, 代码中firing_tss的值跟手册中的都不一致, 到底哪个是对的

### ISSUE THREAD

**Issue by xclord** [RoboSense-LiDAR/rs_driver#41]
BP为例:
float firing_tss[] = 
  {
    0.00f,  2.56f,  5.12f,  7.68f, 10.24f, 12.80f, 15.36f, 17.92f, 
    25.68f, 28.24f, 30.80f, 33.36f, 35.92f, 38.48f, 41.04f, 43.60f,
    1.28f,  3.84f,  6.40f, 8.96f, 11.52f, 14.08f, 16.64f, 19.20f,
    26.96f, 29.52f, 32.08f, 34.64f, 37.20f, 39.76f, 42.32f, 44.88f
  };

手册:
![image](https://github.com/RoboSense-LiDAR/rs_driver/assets/4407606/095b34ae-9ea2-4684-bf32-2ee2f6bb2449)

**Comment by nachovizzo** [comment]
I also have the same question

**Comment by nachovizzo** [comment]
So, we have a problem here, as I also did the experiment with the manual's timestamp and didn't see a noticeable difference ( I was expecting a horrible error, but that was not the case). So now I'm unsure of which one is the correct one.

The biggest difference, and thus the biggest error, depending on which one we pick would be in the "middle" beams, from beam 10 to 25 approx

## Manual timestamps
![image](https://github.com/botsandus/auto-robot/assets/21349875/bc0fecbd-ab94-474a-8763-3dd092e20e8f)

## Driver Timestamps
![image](https://github.com/botsandus/auto-robot/assets/21349875/767a9c30-e480-4baf-bc51-4481a2befef7)

## Difference
![image](https://github.com/botsandus/auto-robot/assets/21349875/87979318-2c13-46a1-aff6-0647d7dea45c)

**Comment by nachovizzo** [comment]
Update: I was using the wrong index, I was looking at the channel number instead of the beam angle. Even when correcting this, the difference between the manual and the driver is still there

## Manual's timestamps
![image](https://github.com/botsandus/auto-robot/assets/21349875/34dcc52d-224d-465b-9a46-583ee19b4094)

## Difference
![image](https://github.com/botsandus/auto-robot/assets/21349875/32141485-0b06-4bb1-b508-6abc38315ecf)

**Comment by FelixHuang18** [comment]
The timestamp has been updated on v1.5.13, close this issue.
